// RST (Relation Symbol Table) - A simplified code intelligence format for LLM navigation.
//
// This format provides a lightweight representation of symbol relationships,
// extracted from SCIP indexes for efficient code navigation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: rst.proto

package rst

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RST is the root message for a Relation Symbol Table
type RST struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Documents     map[string]*Document   `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RST) Reset() {
	*x = RST{}
	mi := &file_rst_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RST) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RST) ProtoMessage() {}

func (x *RST) ProtoReflect() protoreflect.Message {
	mi := &file_rst_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RST.ProtoReflect.Descriptor instead.
func (*RST) Descriptor() ([]byte, []int) {
	return file_rst_proto_rawDescGZIP(), []int{0}
}

func (x *RST) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RST) GetDocuments() map[string]*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`         // Repository identifier (e.g., github.com/sourcegraph/scip)
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"` // Primary language of this RST file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_rst_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_rst_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_rst_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *Metadata) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelativePath  string                 `protobuf:"bytes,1,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	Symbols       map[string]*Symbol     `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_rst_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_rst_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_rst_proto_rawDescGZIP(), []int{2}
}

func (x *Document) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *Document) GetSymbols() map[string]*Symbol {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type Symbol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`                                 // Full SCIP symbol
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`                                     // Symbol kind (FUNC, STRUCT, METHOD, etc.)
	Documentation string                 `protobuf:"bytes,3,opt,name=documentation,proto3" json:"documentation,omitempty"`                   // Documentation string
	ReferenceBy   []string               `protobuf:"bytes,4,rep,name=reference_by,json=referenceBy,proto3" json:"reference_by,omitempty"`    // Symbols that reference this symbol
	DependenceOn  []string               `protobuf:"bytes,5,rep,name=dependence_on,json=dependenceOn,proto3" json:"dependence_on,omitempty"` // Symbols this symbol depends on
	Signature     string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`                           // Function/method signature (e.g., "func foo(bar string) error")
	Line          int32                  `protobuf:"varint,7,opt,name=line,proto3" json:"line,omitempty"`                                    // Line number where symbol is defined
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Symbol) Reset() {
	*x = Symbol{}
	mi := &file_rst_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Symbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symbol) ProtoMessage() {}

func (x *Symbol) ProtoReflect() protoreflect.Message {
	mi := &file_rst_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symbol.ProtoReflect.Descriptor instead.
func (*Symbol) Descriptor() ([]byte, []int) {
	return file_rst_proto_rawDescGZIP(), []int{3}
}

func (x *Symbol) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Symbol) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Symbol) GetDocumentation() string {
	if x != nil {
		return x.Documentation
	}
	return ""
}

func (x *Symbol) GetReferenceBy() []string {
	if x != nil {
		return x.ReferenceBy
	}
	return nil
}

func (x *Symbol) GetDependenceOn() []string {
	if x != nil {
		return x.DependenceOn
	}
	return nil
}

func (x *Symbol) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Symbol) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

var File_rst_proto protoreflect.FileDescriptor

const file_rst_proto_rawDesc = "" +
	"\n" +
	"\trst.proto\x12\x03rst\"\xb4\x01\n" +
	"\x03RST\x12)\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.rst.MetadataR\bmetadata\x125\n" +
	"\tdocuments\x18\x02 \x03(\v2\x17.rst.RST.DocumentsEntryR\tdocuments\x1aK\n" +
	"\x0eDocumentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.rst.DocumentR\x05value:\x028\x01\":\n" +
	"\bMetadata\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"\xae\x01\n" +
	"\bDocument\x12#\n" +
	"\rrelative_path\x18\x01 \x01(\tR\frelativePath\x124\n" +
	"\asymbols\x18\x02 \x03(\v2\x1a.rst.Document.SymbolsEntryR\asymbols\x1aG\n" +
	"\fSymbolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.rst.SymbolR\x05value:\x028\x01\"\xd4\x01\n" +
	"\x06Symbol\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12$\n" +
	"\rdocumentation\x18\x03 \x01(\tR\rdocumentation\x12!\n" +
	"\freference_by\x18\x04 \x03(\tR\vreferenceBy\x12#\n" +
	"\rdependence_on\x18\x05 \x03(\tR\fdependenceOn\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12\x12\n" +
	"\x04line\x18\a \x01(\x05R\x04lineB*Z(github.com/sourcegraph/scip/cmd/scip/rstb\x06proto3"

var (
	file_rst_proto_rawDescOnce sync.Once
	file_rst_proto_rawDescData []byte
)

func file_rst_proto_rawDescGZIP() []byte {
	file_rst_proto_rawDescOnce.Do(func() {
		file_rst_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rst_proto_rawDesc), len(file_rst_proto_rawDesc)))
	})
	return file_rst_proto_rawDescData
}

var file_rst_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rst_proto_goTypes = []any{
	(*RST)(nil),      // 0: rst.RST
	(*Metadata)(nil), // 1: rst.Metadata
	(*Document)(nil), // 2: rst.Document
	(*Symbol)(nil),   // 3: rst.Symbol
	nil,              // 4: rst.RST.DocumentsEntry
	nil,              // 5: rst.Document.SymbolsEntry
}
var file_rst_proto_depIdxs = []int32{
	1, // 0: rst.RST.metadata:type_name -> rst.Metadata
	4, // 1: rst.RST.documents:type_name -> rst.RST.DocumentsEntry
	5, // 2: rst.Document.symbols:type_name -> rst.Document.SymbolsEntry
	2, // 3: rst.RST.DocumentsEntry.value:type_name -> rst.Document
	3, // 4: rst.Document.SymbolsEntry.value:type_name -> rst.Symbol
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_rst_proto_init() }
func file_rst_proto_init() {
	if File_rst_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rst_proto_rawDesc), len(file_rst_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rst_proto_goTypes,
		DependencyIndexes: file_rst_proto_depIdxs,
		MessageInfos:      file_rst_proto_msgTypes,
	}.Build()
	File_rst_proto = out.File
	file_rst_proto_goTypes = nil
	file_rst_proto_depIdxs = nil
}
